/** Reproducible campaign simulations. Only initial chapter entry poses are set.
 * Every subsequent position change is generated by normal movement and gravity.
 * Run: node tests/replay.mjs [--out evidence/campaign-replay.json]
 */
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {resolve} from 'node:path';
import {writeFile} from 'node:fs/promises';
import {createState,step,trace,pickUp,serialize,restore,normalize,sub,dot,add,mul,length} from '../src/engine.mjs';
import {world,initializeCampaign,updateCampaign,interactCampaign,nextHint} from '../src/campaign.mjs';

const STEP=1/60;
export class Pilot {
  constructor(chapter,{hub=false}={}) {
    this.chapter=chapter;this.state=createState(world);initializeCampaign(this.state);
    const entry=world.rooms.find(room=>room.id===`c${chapter}`);
    if(!hub){
      this.state.player={...this.state.player,room:entry.id,p:[...entry.spawn.p],forward:[...entry.spawn.forward],up:[...entry.spawn.up]};
      for(let i=1;i<chapter;i++)this.state.flags[`solved:${i}`]=true;
    }
    this.actions=[];this.ticks=0;this.crossings=[];this.updates();
  }
  updates(){updateCampaign(this.state,0);}
  tick(input={},dt=STEP) {
    const before=this.state.events.length;
    step(world,this.state,input,dt);updateCampaign(this.state,dt);this.ticks++;
    this.crossings.push(...this.state.events.slice(before).filter(event=>event.type==='crossing').map(event=>({portal:event.portal,from:event.from,to:event.to,scale:event.scale})));
  }
  wait(seconds) {for(let i=0;i<Math.ceil(seconds/STEP);i++)this.tick();}
  aim(point) {this.state.player.forward=normalize(sub(point,this.state.player.p));}
  move(point,label='waypoint') {
    const p=this.state.player,expectedRoom=p.room;
    let stalled=0,previous=Infinity;
    for(let i=0;i<30000;i++) {
      assert.equal(this.state.player.room,expectedRoom,`Unexpected portal while walking to ${label}`);
      const delta=sub(point,p.p),flat=sub(delta,mul(p.up,dot(delta,p.up))),distance=length(flat);
      if(distance<.012*p.scale){this.actions.push({action:'walk',room:p.room,p:p.p.map(n=>+n.toFixed(4)),label});return;}
      this.state.player.forward=normalize(flat);
      this.tick({forward:Math.min(1,distance/(3*p.scale*STEP))});
      if(Math.abs(distance-previous)<1e-7)stalled++;else stalled=0;
      previous=distance;
      assert.ok(stalled<30,`Stalled at ${JSON.stringify(p.p)} in ${p.room} toward ${label} ${JSON.stringify(point)}; held=${this.state.held}`);
    }
    assert.fail(`Waypoint timed out: ${label}`);
  }
  through(id) {
    const portal=world.portals.find(p=>p.id===id);assert.ok(portal,`No portal ${id}`);assert.equal(this.state.player.room,portal.room);
    const player=this.state.player;
    const target=add(sub(portal.center,mul(portal.up,portal.height/2)),mul(player.up,1.6*player.scale));
    this.move(add(target,mul(portal.normal,.75*player.scale)),`approach ${id}`);
    const room=player.room;this.state.player.forward=mul(portal.normal,-1);
    for(let i=0;i<180&&this.state.player.room===room;i++)this.tick({forward:1});
    assert.notEqual(this.state.player.room,room,`Portal ${id} did not cross from ${JSON.stringify(this.state.player.p)} (scale ${this.state.player.scale})`);
    assert.equal(this.state.player.room,world.portals.find(p=>p.id===portal.to).room);
    this.actions.push({action:'cross',portal:id,room:this.state.player.room,scale:this.state.player.scale});
  }
  approach(id,side=[0,0,1]) {
    const item=this.state.objects[id]||world.interactables.find(item=>item.id===id);assert.ok(item,`Missing ${id}`);
    assert.equal(this.state.player.room,item.room,`Approach ${id} in wrong room`);
    const p=this.state.player,point=add(item.p,mul(side,1.15*p.scale));
    // Retain the current floor eye coordinate; the target can sit on a low
    // stand. Aiming after walking supplies the required downward view.
    const axis=p.up.findIndex(v=>Math.abs(v)>.5);point[axis]=p.p[axis];
    this.move(point,`reach ${id}`);this.aim(item.p);
    const hit=trace(world,this.state);assert.equal(hit?.id,id,`Expected ray target ${id}, got ${JSON.stringify(hit)} from ${JSON.stringify(p.p)}`);
    return hit;
  }
  take(id,side=[0,0,1]) {this.approach(id,side);assert.equal(pickUp(world,this.state,id),true,`Pickup ${id}`);this.actions.push({action:'take',id});}
  use(id,side=[0,0,1]) {
    this.approach(id,side);
    const result=interactCampaign(this.state,id);assert.ok(result,`Interact ${id}`);this.updates();
    this.actions.push({action:'interact',id,result:result.type});return result;
  }
  align(id) {
    const item=world.interactables.find(item=>item.id===id);this.move(item.p,`observation mark ${id}`);this.aim(item.target);this.wait(item.hold+.15);
    assert.equal(this.state.flags[item.flag],true,`${id} connection did not settle`);this.actions.push({action:'align',id});
    if(item.up)this.move([this.state.player.p[0],item.p[1]+1.1,item.target[2]+3.3],'walk beside the wall compass');
  }
  change(id) {
    const item=world.interactables.find(item=>item.id===id);
    this.use(id,[0,0,this.state.player.p[2]<item.p[2]?-1:1]);this.state.player.forward=normalize(sub(this.state.player.p,item.target));this.wait(1);
    assert.equal(this.state.flags[item.flag],true,`${id} did not rearrange while unobserved`);this.actions.push({action:'look-away',id});
    this.move([item.p[0]-1.1,this.state.player.p[1],this.state.player.p[2]],'step beside the arrangement stand');
  }
  saveRoundtrip() {
    const before=this.state,restored=restore(world,serialize(before));initializeCampaign(restored);
    assert.equal(restored.player.room,before.player.room);assert.equal(restored.player.scale,before.player.scale);
    assert.deepEqual(restored.player.up,before.player.up);assert.deepEqual(restored.player.p,before.player.p);
    assert.deepEqual(restored.solved,before.solved);assert.deepEqual(restored.hints,before.hints);assert.deepEqual(restored.visited,before.visited);
    this.state=restored;this.actions.push({action:'save-restore',room:restored.player.room,scale:restored.player.scale,up:restored.player.up});
  }
  summary() {
    return {chapter:this.chapter,title:world.chapters[this.chapter-1].title,passed:true,simulationSeconds:+(this.ticks*STEP).toFixed(2),frames:this.ticks,portalCrossings:this.crossings.length,finalRoom:this.state.player.room,finalScale:this.state.player.scale,actions:this.actions,crossings:this.crossings};
  }
}

export function runChamber(chapter,pilot=null) {
  const p=pilot||new Pilot(chapter);p.chapter=chapter;
  nextHint(p.state); // Check that a real hint survives each chapter's save.
  switch(chapter) {
    case 1:
      p.through('c1-east');p.through('c1-gallery-out');p.take('weight1');p.through('c1-enclosure');p.through('c1-gallery-in');p.use('plinth1');break;
    case 2:
      p.through('pavilion-front');p.take('weight2');p.through('archive-west');
      p.move([3,1.6,1],'around pavilion east');p.move([3,1.6,-4],'behind pavilion');p.move([0,1.6,-4]);p.through('pavilion-rear');p.use('plinth2');break;
    case 3:
      p.take('weight3');p.through('quarter-in');p.saveRoundtrip();p.use('plinth3');p.through('quarter-out');break;
    case 4:
      p.through('garden-winter');p.take('weight4');p.through('winter-return');p.change('garden-shutter');p.through('garden-summer');p.use('plinth4');break;
    case 5:
      p.align('sight-mark');p.through('sight-in');p.take('weight5');p.through('sight-out');p.use('plinth5',[0,0,-1]);
      p.move([-1.7,1.6,1.85],'beside the filled sightline index');p.move([-1.7,1.6,4.15],'past the sightline index');break;
    case 6:
      p.use('gravity6');p.wait(2);p.move([4.4,6,-5],'walk up the former wall, beside its compass');p.saveRoundtrip();p.through('wall6-in');p.use('plate6');
      p.through('wall6-out');p.use('gravity6wall',[0,0,-1]);p.wait(2);break;
    case 7:
      p.take('weight7');p.through('half7-in');p.through('neutral7-out');p.through('half7-in');p.through('neutral7-out');p.saveRoundtrip();p.through('cabinet7-in');p.use('plinth7');break;
    case 8:
      p.through('transit-collection');p.take('weight8');p.through('collection-return');p.change('transit-shutter');p.through('transit-conservation');p.use('plinth8');break;
    case 9:
      p.take('weight9');p.use('gravity9');p.wait(2);p.align('wall-mark9');p.saveRoundtrip();p.through('wall9-in');p.use('plinth9');break;
    case 10:
      p.through('final-pavilion');p.take('weight10');p.through('final-half');p.use('plinth10');p.saveRoundtrip();p.move([1,.8,1],'beside OPEN index');p.move([1,.8,-1],'past OPEN index');p.through('final-restore');
      p.change('final-shutter');p.through('final-hold-in');p.use('gravity10');p.wait(2);p.align('final-mark');p.through('exit-created');p.use('last-ledger');break;
    default:throw new Error(`Unknown chapter ${chapter}`);
  }
  assert.equal(p.state.flags[`complete:${chapter}`],true,`Chapter ${chapter} not complete`);
  assert.ok(p.state.solved.includes(chapter),`Chapter ${chapter} not recorded`);
  p.saveRoundtrip();return {pilot:p,report:p.summary()};
}

export function runFullCampaign() {
  const p=new Pilot(1,{hub:true});
  for(let chapter=1;chapter<=10;chapter++) {
    p.move([0,1.6,8],'the hub approach');
    if(chapter===10){p.move([3,1.6,8],'beside the court reading stand');p.move([3,1.6,3],'past the court note stand');p.move([3,1.6,-6],'around the central exhibition');p.move([0,1.6,-6],'toward the final doorway');}
    p.through(`hub-${chapter}`);
    runChamber(chapter,p);
    if(chapter===10)break;
    switch(chapter) {
      case 2:p.through('archive-east');p.move([3,1.6,-4],'behind pavilion on return');p.move([3,1.6,1],'around pavilion on return');break;
      case 4:p.through('summer-return');break;
      case 7:
        p.through('cabinet7-out');p.through('neutral7-in');p.through('half7-out');p.through('neutral7-in');p.through('half7-out');break;
      case 8:p.through('conservation-return');break;
      case 9:p.through('wall9-out');p.use('gravity9wall',[0,0,-1]);p.wait(2);break;
    }
    assert.equal(p.state.player.scale,1,`Chapter ${chapter} returned at original measure`);
    assert.deepEqual(p.state.player.up,[0,1,0],`Chapter ${chapter} restored ordinary gravity`);
    p.through(`c${chapter}-hub`);
  }
  assert.deepEqual(p.state.solved,[1,2,3,4,5,6,7,8,9,10]);assert.equal(p.state.flags.finished,true);
  return {pilot:p,report:{...p.summary(),chapter:'complete campaign',title:'Hub to departure ledger',completedChapters:[...p.state.solved],method:'One continuous journey from createState(world), with no player position assignment after initial spawn; normal movement and visible interactions throughout, plus save/restore at chapter checkpoints.'}};
}

if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)) {
  const reports=[];
  for(let chapter=1;chapter<=10;chapter++) {
    try {const {report}=runChamber(chapter);reports.push(report);console.log(`PASS ${chapter}: ${report.title} (${report.portalCrossings} crossings, ${report.simulationSeconds}s simulated)`);}
    catch(error){console.error(`FAIL ${chapter}: ${error.stack}`);process.exitCode=1;reports.push({chapter,passed:false,error:error.message});}
  }
  try{const {report}=runFullCampaign();reports.push(report);console.log(`PASS continuous campaign: ${report.portalCrossings} crossings, ${report.simulationSeconds}s simulated, all ten indices and departure ledger`);}
  catch(error){console.error(`FAIL continuous campaign: ${error.stack}`);process.exitCode=1;reports.push({chapter:'complete campaign',passed:false,error:error.message});}
  const result={method:'Per-chamber simulation: initial pose at each safe entrance; all subsequent navigation uses step, all pickups/interactions require trace, actual campaign predicates',node:process.version,platform:process.platform,date:new Date().toISOString(),reports};
  const outIndex=process.argv.indexOf('--out');if(outIndex>=0&&process.argv[outIndex+1])await writeFile(process.argv[outIndex+1],JSON.stringify(result,null,2)+'\n');
}
