/** Original procedural museum score. All audio is generated locally after a user gesture. */
export class MuseumAudio{
  constructor(settings){this.settings=settings;this.ctx=null;this.nodes=[];this.lastStep=0;this.chapter=-1;}
  async start(){if(!this.ctx){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;this.ctx=new AC();this.master=this.ctx.createGain();this.master.gain.value=this.settings.volume??.35;this.master.connect(this.ctx.destination);this.ambient=this.ctx.createGain();this.ambient.gain.value=.09;this.ambient.connect(this.master);for(const f of [65.406,98,130.813,196.0]){const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sine';o.frequency.value=f;g.gain.value=.18;o.connect(g);g.connect(this.ambient);o.start();this.nodes.push({o,g});}}await this.ctx.resume();this.setVolume(this.settings.volume??.35);}
  setVolume(v){if(this.ctx)this.master.gain.setTargetAtTime(v,this.ctx.currentTime,.12);}
  room(chapter){if(!this.ctx||this.chapter===chapter)return;this.chapter=chapter;const ratio=[1,1,1.125,1.25,1.125,1.3333,1.5,1.25,1.125,1.3333,1.5][chapter]||1;this.nodes.forEach(({o},i)=>o.frequency.setTargetAtTime([65.406,98,130.813,196][i]*ratio,this.ctx.currentTime,1.8));}
  tone(f,time=.8,volume=.13,delay=0){if(!this.ctx)return;const t=this.ctx.currentTime+delay,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+time);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+time+.02);o.onended=()=>{o.disconnect();g.disconnect();};}
  event(type){if(['solved','ending'].includes(type)){[261.63,329.63,392,523.25].forEach((f,i)=>this.tone(f,2,.15,i*.18));}else if(type==='socket')this.tone(392,1,.13);else if(type==='connection'){this.tone(293.66,1.5,.11);this.tone(440,1.8,.08,.1);}else if(type==='arrangement'){this.tone(110,.25,.16);this.tone(164.81,.5,.08,.13);}else if(type==='gravity'){this.tone(82.4,1.7,.18);this.tone(164.81,1.5,.06,.12);}else if(type==='pickup')this.tone(330,.2,.08);else if(type==='drop')this.tone(147,.2,.11);}
  footstep(speed,elapsed,scale){if(!this.ctx||speed<.1)return;if(elapsed-this.lastStep>(speed>3.5?.3:.46)){this.lastStep=elapsed;this.tone(76+Math.random()*22,.09,.075);this.tone(210+Math.random()*60,.045,.025,.02);}}
  pause(paused){if(this.ctx)this.ambient.gain.setTargetAtTime(paused?.025:.09,this.ctx.currentTime,.6);}
}
