import * as engine from './engine.mjs';
import {world,initializeCampaign,currentChapter,updateCampaign,interactCampaign,recallWeights,nextHint} from './campaign.mjs';
import {MuseumRenderer} from './render.mjs';
import {MuseumAudio} from './audio.mjs';

const $=id=>document.getElementById(id),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const SAVE='impossible-museum-save-v1',SETTINGS='impossible-museum-settings-v1';
let settings={volume:.35,sensitivity:1,fov:72,quality:'high',reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,invertY:false};
try{Object.assign(settings,JSON.parse(localStorage.getItem(SETTINGS)||'{}'));}catch{}
let rawSave;try{rawSave=localStorage.getItem(SAVE);}catch{}
let state=rawSave?engine.restore(world,rawSave):engine.createState(world);initializeCampaign(state);
let started=false,modalOpen=false,devOpen=false,notebookTab='map',keys=new Set(),drag=false,last=performance.now(),saveTime=0,uiTime=0,toastTimer,cardTimer,restoring=false,lastFocus=null;
let render,audio=new MuseumAudio(settings),fpsSamples=[],lastChapter=-1,errors=[];
const testMode=new URLSearchParams(location.search).has('test');
function reportError(error){errors.push(String(error));console.error(error);}
window.addEventListener('error',e=>reportError(e.error||e.message));
window.addEventListener('unhandledrejection',e=>reportError(e.reason));

function toast(text,duration=4700){if(!text)return;$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),duration);}
function save(){if(!started)return;try{localStorage.setItem(SAVE,engine.serialize(state));$('save-status').textContent='Saved locally';}catch{$('save-status').textContent='Save unavailable';toast('This browser cannot store progress. Use Notebook → Save file to export your visit.',6500);}}
function applySettings(){settings.volume=Math.min(1,Math.max(0,Number(settings.volume)||0));settings.fov=Math.min(95,Math.max(55,Number(settings.fov)||72));settings.sensitivity=Math.min(2.5,Math.max(.25,Number(settings.sensitivity)||1));if(render){render.settings=settings;render.renderer.setPixelRatio(Math.min(devicePixelRatio,settings.quality==='low'?1:1.5));render.resize();}audio.setVolume(settings.volume);try{localStorage.setItem(SETTINGS,JSON.stringify(settings));}catch{}}
function showModal(title,body,eyebrow='THE MUSEUM'){lastFocus=document.activeElement;modalOpen=true;keys.clear();if(document.pointerLockElement)document.exitPointerLock();$('modal-title').textContent=title;$('modal-eyebrow').textContent=eyebrow;$('modal-body').innerHTML=body;$('modal-backdrop').hidden=false;audio.pause(true);$('modal-close').focus();}
function closeModal(relock=true){modalOpen=false;$('modal-backdrop').hidden=true;audio.pause(false);keys.clear();if(started&&relock&&!devOpen)requestLook();else lastFocus?.focus?.();}
async function requestLook(){try{await $('world').requestPointerLock();}catch{toast('Click and drag to look, or use the arrow keys. W A S D still move.');}}
function noteModal(title,text){showModal(title,`<p class="note-copy">${escape(text)}</p><div class="button-row"><button class="primary" id="read-done">Return to the exhibition ↗</button></div>`,'FROM THE CURATOR’S COLLECTION');$('read-done').onclick=()=>closeModal();}
function hint(){const h=nextHint(state);showModal(h.title,`<p class="note-copy">${escape(h.text)}</p><div class="button-row"><button class="primary" id="hint-done">Try this</button><button id="hint-next">A more direct hint</button></div>`,'A LITTLE GUIDANCE');$('hint-done').onclick=()=>closeModal();$('hint-next').onclick=hint;save();}
function showCard(chapter){if(!chapter)return;const box=$('chapter-card');box.querySelector('.eyebrow').textContent=`EXHIBITION ${String(chapter.id).padStart(2,'0')} · ${chapter.rule.toUpperCase()}`;box.querySelector('h2').textContent=chapter.title;box.querySelector('p').textContent=chapter.objective;box.classList.add('show');clearTimeout(cardTimer);cardTimer=setTimeout(()=>box.classList.remove('show'),6000);}
function interact(){const hit=engine.trace(world,state);if(!hit)return;if(hit.kind==='object'){if(engine.pickUp(world,state,hit.id))toast('Index weight in hand. Q sets it down. Carry it to a matching plinth.',2400);return;}
  const result=interactCampaign(state,hit.id);if(!result)return;
  if(result.type==='note')noteModal(result.title,result.text);
  else if(result.type==='ending'){updateCampaign(state,0);audio.event('ending');showModal('A door into morning',`<p class="note-copy">${escape(result.text)}</p><div class="button-row"><button class="primary" id="ending-stay">Stay a little longer</button><button id="ending-notebook">Open the completed notebook</button></div>`,'TEN EXHIBITIONS · ONE WAY OUT');$('ending-stay').onclick=()=>closeModal();$('ending-notebook').onclick=()=>notebook();}
  else if(result.text)toast(result.text);
  updateCampaign(state,0);save();
}
function recover(toHub=false){if(toHub)state.checkpoint='hub';engine.recover(world,state);initializeCampaign(state);toast(toHub?'You return to the court. Every discovery is retained.':'You return to this exhibition’s entrance at your original measure. Loose weights return to their stands.',6000);save();}
function pauseMenu(){showModal('A moment between rooms',`<p>${escape(currentChapter(state)?.objective||'The next numbered doorway in the court continues your route.')}</p><div class="button-row"><button class="primary" id="resume">Continue the visit ↗</button><button id="pause-notebook">Notebook & map</button><button id="pause-settings">Sound & comfort</button><button id="pause-controls">Controls</button></div><div class="button-row"><button id="pause-recover">Recover to exhibition entrance</button><button id="pause-court">Return to the court</button><button id="pause-save">Save to a file</button></div><p class="fine-print">Progress saves automatically on this browser. Recovery recalls loose weights and restores your measure; completed indexes remain in place.</p>`,'THE VISIT IS PAUSED');$('resume').onclick=()=>closeModal();$('pause-notebook').onclick=()=>notebook();$('pause-settings').onclick=settingsMenu;$('pause-controls').onclick=controls;$('pause-recover').onclick=()=>{recover();closeModal();};$('pause-court').onclick=()=>{recover(true);closeModal();};$('pause-save').onclick=exportSave;}
function controls(onboarding=false){showModal(onboarding?'Your visitor’s card':'Moving through the museum',`<p>Each exhibition teaches a reliable rule. The numbered doors in the court form your route. Read the curator’s notes and bring index weights to matching plinths.</p><dl class="controls-grid"><dt>W A S D</dt><dd>Walk. Hold Shift to walk faster.</dd><dt>Mouse / arrow keys</dt><dd>Look. Click the scene to capture your mouse; Escape releases it. Click and drag also works.</dd><dt>E</dt><dd>Read, use, pick up a weight, or place it in a plinth.</dd><dt>Q</dt><dd>Set down a carried weight.</dd><dt>H</dt><dd>A hint, from subtle to specific.</dd><dt>J / Escape</dt><dd>Notebook and map / pause.</dd><dt>R</dt><dd>Recover to this exhibition’s entrance. Completed indexes remain.</dd><dt>F3</dt><dd>Developer view: inspect connections, triggers and puzzle state.</dd></dl><p class="fine-print">There is no jump, combat, timer or death. Scale changes affect movement and reach. Gravity changes have no fall damage. Desktop keyboard and mouse are required.</p><div class="button-row"><button class="primary" id="controls-done">${onboarding?'Begin the visit ↗':'Return to the exhibition'}</button></div>`,onboarding?'ADMIT ONE · TAKE YOUR TIME':'VISITOR INFORMATION');$('controls-done').onclick=()=>{state.flags.onboarded=true;closeModal();if(onboarding)toast('Begin at exhibition 01 on the left side of the court. E reads the nearby curator’s note.',6500);save();};}
function notebook(tab=notebookTab){notebookTab=tab;
  const chapter=currentChapter(state);let body=`<div class="tab-row">${[['map','Exhibitions'],['notes','Collected notes'],['save','Save & recovery']].map(([id,title])=>`<button data-tab="${id}" class="${tab===id?'selected':''}">${title}</button>`).join('')}</div>`;
  if(tab==='map'){
    body+=`<p>${chapter?escape(chapter.objective):'The court remembers every restored index. Follow the next illuminated numbered doorway.'}</p><div class="chapter-list">`;
    for(const c of world.chapters){const done=state.solved.includes(c.id),open=c.id===1||state.solved.includes(c.id-1);body+=`<div class="chapter-entry ${!open?'locked':''} ${done?'complete':''} ${chapter?.id===c.id?'current':''}"><span>${done?'✓':String(c.id).padStart(2,'0')}</span><div><h3>${escape(c.title)}</h3><p>${done?escape(c.reflection):open?escape(c.rule):'Awaiting the previous index'}</p></div></div>`;}body+='</div>';
    if(chapter?.id===10)body+=`<p>OPEN ${state.flags['final-open']?'✓':'○'} · HOLD ${state.flags['final-hold']?'✓':'○'} · RELEASE ${state.flags['final-release']?'✓':'○'}</p>`;
  }else if(tab==='notes')body+=`<div class="notes-list">${state.journal.length?state.journal.map(n=>`<details><summary>${escape(n.title||'Collected note')}</summary><p>${escape(n.text||'')}</p></details>`).join(''):'<p>The notebook is waiting. Read a curator’s note with E, or restore an index.</p>'}</div>`;
  else body+=`<p>Your visit is saved automatically on this browser. Export a save to continue in another browser or keep a backup.</p><div class="button-row"><button id="export-save">Save to a file</button><button id="recall-weights">Recall loose weights</button><button id="notebook-recover">Recover to exhibition entrance</button><button id="notebook-court">Return to the court</button></div><div class="file-row"><label for="import-save">Restore a save file</label><input type="file" id="import-save" accept=".json,application/json"></div><p class="fine-print">Recovery restores your original measure and recalls loose weights. It preserves every completed index, settled connection, collected note and finale correction.</p><div class="button-row"><button class="danger" id="new-visit">Begin a new visit…</button></div>`;
  showModal('The visitor’s notebook',body,`${String(state.solved.length).padStart(2,'0')} OF 10 INDEX PLATES`);
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>notebook(b.dataset.tab));
  if(tab==='save'){$('export-save').onclick=exportSave;$('recall-weights').onclick=()=>{recallWeights(state);save();closeModal();};$('notebook-recover').onclick=()=>{recover();closeModal();};$('notebook-court').onclick=()=>{recover(true);closeModal();};$('import-save').onchange=importSave;$('new-visit').onclick=()=>{showModal('Begin again?',`<p>This replaces the saved visit on this browser. Save your current visit to a file first if you would like to return to it.</p><div class="button-row"><button id="backup-first">Save current visit</button><button class="danger" id="confirm-new">Begin a new visit</button><button id="cancel-new">Keep exploring</button></div>`,'A NEW NOTEBOOK');$('backup-first').onclick=exportSave;$('cancel-new').onclick=()=>notebook('save');$('confirm-new').onclick=()=>{setState(engine.createState(world));save();controls(true);};};}
}
function settingsMenu(){showModal('Sound & comfort',`<div class="settings-grid"><label>Volume <input id="volume" type="range" min="0" max="1" step=".05" value="${settings.volume}"></label><label>Look sensitivity <input id="sensitivity" type="range" min=".25" max="2.5" step=".05" value="${settings.sensitivity}"></label><label>Field of view <input id="fov" type="range" min="55" max="95" step="1" value="${settings.fov}"></label><label>Rendering <select id="quality"><option value="high" ${settings.quality==='high'?'selected':''}>Full — two doorway depths</option><option value="low" ${settings.quality==='low'?'selected':''}>Light — one doorway depth</option></select></label><label class="check"><input id="reduced-motion" type="checkbox" ${settings.reducedMotion?'checked':''}> Reduce decorative motion & snap gravity roll</label><label class="check"><input id="invert-y" type="checkbox" ${settings.invertY?'checked':''}> Invert vertical mouse look</label></div><p class="fine-print">Sound is an original, quiet procedural score. Every audio cue also has a visible message. If movement is uncomfortable, widen the view or enable reduced motion. The gravity rule still changes your movement orientation.</p><div class="button-row"><button class="primary" id="settings-done">Done</button></div>`,'VISITOR PREFERENCES');
  for(const [id,key]of [['volume','volume'],['sensitivity','sensitivity'],['fov','fov'],['quality','quality'],['reduced-motion','reducedMotion'],['invert-y','invertY']])$(id).oninput=()=>{settings[key]=$(id).type==='checkbox'?$(id).checked:$(id).tagName==='SELECT'?$(id).value:Number($(id).value);applySettings();};$('settings-done').onclick=()=>closeModal(started);
}
function exportSave(){save();const blob=new Blob([engine.serialize(state)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Museum-Visit.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);toast('Your visit has been saved to a file.');}
async function importSave(e){const file=e.target.files?.[0];if(!file)return;try{if(file.size>2e6)throw Error('This file is too large.');const text=await file.text(),parsed=JSON.parse(text);if(parsed.version!==1||!parsed.player||!parsed.objects)throw Error('This is not a museum save.');setState(engine.restore(world,text));started=true;$('start-screen').hidden=true;showPlayUI();save();closeModal();toast('Your visit is restored.');}catch(err){toast(`Could not restore this file. ${err.message}`);}}
function setState(next){state=next;initializeCampaign(state);render.state=state;lastChapter=-1;}
function showPlayUI(){for(const id of ['hud','reticle','play-footer'])$(id).hidden=false;}
async function start(){started=true;$('start-screen').hidden=true;showPlayUI();await audio.start();if(!state.flags.onboarded)controls(true);else{requestLook();toast('Your visit continues. J opens the notebook and H offers a hint.',3500);}save();}

function handleEvents(){for(const e of state.events.splice(0)){audio.event(e.type);if(e.type==='solved'){showCard(world.chapters[e.chapter-1]);toast(`Index ${String(e.chapter).padStart(2,'0')} restored. ${e.chapter<10?'The next doorway is illuminated in the court.':'The route is complete.'}`,6500);save();}else if(['arrangement','connection','outside'].includes(e.type)){toast(e.text);save();}else if(e.type==='crossing'){audio.room(currentChapter(state)?.id||0);save();}else if(e.type==='scaleBlocked')toast('This measuring route has reached its supported limit. Reverse the measure, or recover with R.');else if(e.type==='dropBlocked')toast('There is not enough clear space to set the weight down. Step back and try again.');else if(e.type==='gravityBlocked')toast('There is not enough space to change the floor here. Step away from the exhibit.');}}

function updateHUD(){const r=world.rooms.find(r=>r.id===state.player.room),c=currentChapter(state);$('room-title').textContent=r.name;$('chapter-number').textContent=c?`EXHIBITION ${String(c.id).padStart(2,'0')} · ${c.rule.toUpperCase()}`:'THE MUSEUM';$('plates').textContent=`${String(state.solved.length).padStart(2,'0')} / 10`;const s=state.player.scale;$('measure').querySelector('b').textContent=s===1?'1 : 1':s<1?`1 : ${Number((1/s).toFixed(2))}`:`${Number(s.toFixed(2))} : 1`;$('held-label').textContent=state.held?`Carrying ${state.objects[state.held].size.toFixed(2)} m weight`:'';
  const hit=engine.trace(world,state),it=hit?hit.kind==='object'?state.objects[hit.id]:world.interactables.find(i=>i.id===hit.id):null;
  $('prompt').hidden=!it||modalOpen||devOpen;$('reticle').classList.toggle('active',!!it);if(it){$('prompt').querySelector('span').textContent=hit.kind==='object'?`Take ${it.label} · ${it.size.toFixed(2)} m`:it.type==='socket'?(state.flags[it.flag]?'Index complete':state.held?`Place weight · ${it.acceptSize.toFixed(2)} m`:`${it.label} · ${it.acceptSize.toFixed(2)} m`):it.type==='memory'&&state.flags[it.flag]?'Index collected':it.label;}
  const marker=world.interactables.find(i=>i.room===r.id&&i.type==='align'&&(state.flags[`charge:${i.id}`]||0)>0&&!state.flags[i.flag]);$('alignment').hidden=!marker;if(marker)$('alignment').querySelector('i').style.width=`${100*state.flags[`charge:${marker.id}`]/marker.hold}%`;
  if(c&&lastChapter!==c.id){lastChapter=c.id;showCard(c);}if(!c)lastChapter=0;
}
function devMap(){const room=world.rooms.find(r=>r.id===state.player.room),size=300,x=(v)=>(v-room.bounds.min[0])/(room.bounds.max[0]-room.bounds.min[0])*size,z=(v)=>(v-room.bounds.min[2])/(room.bounds.max[2]-room.bounds.min[2])*size;
  const links=world.portals.filter(p=>p.room===room.id),items=world.interactables.filter(i=>i.room===room.id);
  return `<svg viewBox="-8 -8 316 316" aria-label="Room top view"><rect x="0" y="0" width="300" height="300" fill="none" stroke="#9bbaa9"/>${(room.solids||[]).filter(s=>engine.condition(state,s.requires)).map(s=>`<rect x="${x(s.min[0])}" y="${z(s.min[2])}" width="${x(s.max[0])-x(s.min[0])}" height="${z(s.max[2])-z(s.min[2])}" fill="#99bab855"/>`).join('')}${links.map(p=>`<circle cx="${x(p.center[0])}" cy="${z(p.center[2])}" r="5" fill="${engine.condition(state,p.requires)?'#dabc75':'#526371'}"/><line x1="${x(p.center[0])}" y1="${z(p.center[2])}" x2="${x(p.center[0]+p.normal[0])}" y2="${z(p.center[2]+p.normal[2])}" stroke="#dabc75"/>`).join('')}${items.map(i=>`<circle cx="${x(i.p[0])}" cy="${z(i.p[2])}" r="3" fill="${i.type==='align'?'#d3a6ef':'#87bbb9'}"/>`).join('')}<circle cx="${x(state.player.p[0])}" cy="${z(state.player.p[2])}" r="5" fill="#fff5d7"/><line x1="${x(state.player.p[0])}" y1="${z(state.player.p[2])}" x2="${x(state.player.p[0]+state.player.forward[0]*2)}" y2="${z(state.player.p[2]+state.player.forward[2]*2)}" stroke="#fff5d7"/></svg>`;
}
function developer(){const r=world.rooms.find(r=>r.id===state.player.room);$('developer').innerHTML=`<h2>Spatial inspector <button id="dev-close">Close · F3</button></h2><p>Read-only live geometry and puzzle diagnostics.<br>Room-local metres. Gold: portals · teal: interactions · violet: sightline marks.</p>${devMap()}<p class="performance">${fpsSamples.length?Math.round(1000/(fpsSamples.reduce((a,b)=>a+b,0)/fpsSamples.length)):0} FPS · ${render.metrics.passes} views · ${render.metrics.calls} calls · ${render.metrics.triangles.toLocaleString()} triangles</p><h3>Pose / carried object</h3><pre>${escape(JSON.stringify({room:r.id,p:state.player.p.map(v=>+v.toFixed(3)),forward:state.player.forward.map(v=>+v.toFixed(3)),up:state.player.up,scale:state.player.scale,held:state.held},null,2))}</pre><h3>Connections</h3>${world.portals.filter(p=>p.room===r.id).map(p=>{const d=world.portals.find(q=>q.id===p.to),open=engine.condition(state,p.requires)&&engine.condition(state,d.requires);return `<div class="link ${open?'':'off'}">${escape(p.id)} → ${escape(d.room)}<br>×${+(d.height/p.height).toFixed(3)} · up [${p.up}] → [${d.up}] · ${open?'OPEN':'CLOSED'}<br>condition ${escape(JSON.stringify(p.requires||true))}</div>`;}).join('')}<h3>Triggers / puzzle states</h3><pre>${escape(JSON.stringify(world.interactables.filter(i=>i.room===r.id).map(i=>({id:i.id,type:i.type,p:i.p,flag:i.flag,value:state.flags[i.flag],target:i.target,armed:state.flags[`armed:${i.id}`],charge:state.flags[`charge:${i.id}`]})),null,2))}</pre><h3>Flags</h3><pre>${escape(JSON.stringify(state.flags,null,2))}</pre>`;$('dev-close').onclick=toggleDev;}
function toggleDev(){devOpen=!devOpen;$('developer').hidden=!devOpen;if(devOpen){if(document.pointerLockElement)document.exitPointerLock();keys.clear();developer();}else if(started&&!modalOpen)requestLook();}

document.addEventListener('keydown',e=>{
  if(e.key==='Tab'&&modalOpen){const focusable=[...$('modal').querySelectorAll('button,input,select,summary,a[href]')].filter(n=>!n.disabled),first=focusable[0],end=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){end?.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===end){first?.focus();e.preventDefault();}return;}
  if(e.code==='F3'){e.preventDefault();toggleDev();return;}
  if(e.code==='Escape'){e.preventDefault();if(modalOpen)closeModal(false);else if(started)pauseMenu();return;}
  if(!started||modalOpen||devOpen||['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;
  if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;
  if(e.code==='KeyE')interact();else if(e.code==='KeyQ')engine.drop(world,state);else if(e.code==='KeyH')hint();else if(e.code==='KeyJ')notebook();else if(e.code==='KeyR')recover();
});
document.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();drag=false;});
document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();save();if(started&&!modalOpen)pauseMenu();}});
document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&started&&!modalOpen&&!devOpen&&!testMode){keys.clear();pauseMenu();}});
$('world').addEventListener('mousedown',e=>{if(!started||modalOpen||devOpen)return;if(e.button===0){drag=true;if(!document.pointerLockElement)requestLook();}});document.addEventListener('mouseup',()=>drag=false);
document.addEventListener('mousemove',e=>{if(!started||modalOpen||devOpen)return;if(document.pointerLockElement||drag)engine.look(state,e.movementX*.002*settings.sensitivity,e.movementY*.002*settings.sensitivity*(settings.invertY?-1:1));});
$('modal-close').onclick=()=>closeModal(started);$('start-button').onclick=start;$('start-settings').onclick=()=>{audio.start();settingsMenu();};$('journal-button').onclick=()=>notebook();$('pause-button').onclick=pauseMenu;
window.addEventListener('resize',()=>render?.resize());window.addEventListener('beforeunload',save);

try{
  render=new MuseumRenderer($('world'),world,state,settings);applySettings();if(rawSave)$('start-button').innerHTML=`Continue the visit <span>↗</span>`;
  const cinematic={room:'hub',p:[10,2.7,12],forward:engine.normalize([-.52,-.045,-.85]),up:[0,1,0],velocity:[0,0,0],scale:1};
  function loop(now){const realDt=Math.min(.08,(now-last)/1000);last=now;
    if(started&&!modalOpen&&!devOpen){engine.look(state,((keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0))*realDt*1.45,((keys.has('ArrowDown')?1:0)-(keys.has('ArrowUp')?1:0))*realDt);const input={forward:(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0),strafe:(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),sprint:keys.has('ShiftLeft')||keys.has('ShiftRight')};engine.step(world,state,input,realDt);updateCampaign(state,realDt);audio.footstep(Math.hypot(input.forward,input.strafe)*(input.sprint?4.8:3),state.elapsed,state.player.scale);handleEvents();saveTime+=realDt;if(saveTime>5){saveTime=0;save();}}
    if(!started){const original=state.player;state.player=cinematic;render.render(realDt);state.player=original;}else render.render(modalOpen?0:realDt);
    fpsSamples.push(realDt*1000);if(fpsSamples.length>120)fpsSamples.shift();uiTime+=realDt;if(uiTime>.1){if(started)updateHUD();if(devOpen)developer();uiTime=0;}
    requestAnimationFrame(loop);
  }
  requestAnimationFrame(loop);
  // Deliberate diagnostic surface used by reproducible browser verification; normal play never invokes it.
  window.museum={get state(){return state;},world,engine,get renderer(){return render;},get errors(){return errors;},get audio(){return audio;},get paused(){return modalOpen||!started;},get settings(){return settings;},save,setState,start,closeModal,interact,update:dt=>{engine.step(world,state,{},dt);updateCampaign(state,dt);},snapshot:()=>({state:JSON.parse(engine.serialize(state)),metrics:{...render.metrics},errors:[...errors]})};
}catch(err){reportError(err);const el=document.createElement('div');el.className='fatal';el.innerHTML=`<strong>The museum could not open its 3D view.</strong><p>This game requires a desktop browser with WebGL 2 and hardware acceleration. Try a current Chrome, Edge or Firefox browser.</p><p>${escape(err.message)}</p><p>Launch with <b>Start Museum.cmd</b> or <b>node tools/serve.mjs</b>; opening index.html directly is not supported.</p>`;document.body.append(el);}
